### ISSUE TITLE
The custom UrlGenerator should not typehint the implementation

### ISSUE THREAD

**Issue by stof** [francisbesset/Gitiki#2]
Typehinting should happen on UrlGeneratorInterface instead (maybe requiring more of the routing interfaces too)

**Comment by francisbesset** [comment]
Good point!

**Comment by francisbesset** [comment]
Hum... but how to with `Symfony\Component\Routing\Generator\ConfigurableRequirementsInterface` if the "real" url generator implements or not the interface?

Maybe my UrlGenerator implements `ConfigurableRequirementsInterface` and methods `setStrictRequirements()` and `isStrictRequirements()` check if the "real" url generator implement `ConfigurableRequirementsInterface` and throw an exception if not?

**Comment by stof** [comment]
For `setStrictRequirements`, make it a no-op if the inner generator does not implement it. For `isStrictRequirements`, return a fixed value in this case (I would say `true` as requirements were always strict before we added this feature in Symfony)
