### ISSUE TITLE
The page directory name contains a dot throws exception

### ISSUE THREAD

**Issue by vaclavpavek** [francisbesset/Gitiki#5]
InvalidParameterException in UrlGenerator.php line 163:

Parameter "path" for route "page_dir" must match "([\w\d-/]+/|)" ("v3.x/" given) to generate a corresponding URL.

**Comment by francisbesset** [comment]
Fixed by https://github.com/gitiki/Gitiki/commit/8593bd39dc740e65ae31075d32f49dddbdab805b.

Thank you!
